Metrics/LineLength:
  Max: 160

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Semicolon:
  Enabled: false

Lint/Eval:
  Enabled: false

AllCops:
  Exclude:
    - 'tmp/**/*'

Metrics/AbcSize:
  Max: 20
