require 'forwardable'

require 'delegate_matcher/version'
require 'delegate_matcher/expected'
require 'delegate_matcher/dispatcher'
require 'delegate_matcher/delegate'
require 'delegate_matcher/actual'
require 'delegate_matcher/delegate_to'
require 'delegate_matcher/delegate_to_method'
require 'delegate_matcher/delegate_to_constant'
require 'delegate_matcher/delegate_to_class_variable'
require 'delegate_matcher/delegate_to_instance_variable'
require 'delegate_matcher/delegate_to_object'
require 'delegate_matcher/delegate_factory'

require 'delegate_matcher/delegate_matcher'
